<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tvSchedule[
<!ELEMENT tvSchedule (channel+)>
<!ELEMENT channel (banner,day+)>
<!ELEMENT banner (#PCDATA)>
<!ELEMENT day (date,(holiday|programSlot+)+)>
<!ELEMENT holiday (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT programSlot (time,title,description?)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
]>

<tvSchedule>
    <channel>
        <banner>Nombre</banner>
        <day>
            <date>Fecha</date>
            <holiday>Vacaciones</holiday>
        </day>
    </channel>


    <channel>
        <banner>Nombre</banner>
        <day>
            <date>Fecha</date>
            <programSlot>
                <time>tiempo</time>
                <title>titulo</title>
                <description>Descripcion</description>
            </programSlot>
        </day>
    </channel>
</tvSchedule>